---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: venky-app1
  labels:
    app: venky-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: venky-app1
  template:
    metadata:
      labels:
        app: venky-app1
    spec:
      containers:
      - name: mc-app
        image: gadigevenky/batch13:4
        ports:
        - containerPort: 8080

  

